.github/workflows/deploy.yml

Applying same changes as https://github.com/AdobeDocs/dev-site-documentation-template/pull/155

add redocly license key

---

src/pages/index.md

Update overview for initial deploy

---

src/pages/guides/usage/index.md
src/pages/index.md

initial deploy

---

src/pages/api/index.md

updated API spec location in Redocly block

---

src/pages/getting_started/index.md
src/pages/getting_started/usage/index.md
src/pages/guides/index.md
src/pages/guides/tts/index.md
static/openapi/ttsapi.json

- update Authentication scopes
- add Frame.io developer APIs to storage options
- update supported locale codes
- update supported text prompt formats
- update supported input audio formats
- update supported background types
- update guides for technical details and sample requests
- update Open API Spec
Engg team review of the documentation for TTS Avatar.

Spec and Technical updates

---

src/pages/getting_started/usage/index.md
static/openapi/ttsapi.json

- update media type for output media
- update rate limits
- update color background property

Reviews as per PM inputs

---

src/pages/getting_started/index.md
src/pages/getting_started/usage/index.md
src/pages/guides/index.md
src/pages/guides/tts/index.md
static/openapi/ttsapi.json

- update Authentication scopes
- add Frame.io developer APIs to storage options
- update supported locale codes
- update supported text prompt formats
- update supported input audio formats
- update supported background types
- update guides for technical details and sample requests
- update Open API Spec
Engg team review of the documentation for TTS Avatar.

Spec and Technical updates - promote to prod

---

src/pages/getting_started/usage/index.md
src/pages/guides/index.md
src/pages/guides/tts/index.md
static/openapi/ttsapi.json

- drop SSML input for Generate Speech
- drop SSML input for Generate Avatar
- add invalid_json for both submit endpoints
- add error for Unsafe Script Prompt

Drop SSML Input from TTS Avatar APIs

---

static/openapi/ttsapi.json

Address Review Comments

---

src/pages/getting_started/usage/index.md
static/openapi/ttsapi.json

Updated Error responses as per API Style Guide.
Change verified on stage endpoint- https://developer-stage.adobe.com/audio-video-firefly-services/

Updated Error responses as per API Style Guide

---

gatsby-config.js
src/pages/getting_started/usage/index.md
src/pages/guides/avatar/index.md
src/pages/guides/index.md
src/pages/index.md
static/openapi/ttsapi.json

- gatsby-config.js -- update navigation for TTS page to be the default guides page, remove Avatar page.
- src/pages/index.md -- remove Avatar information.
- src/pages/guides/index.md -- backup the page's original contents in src/pages/guides/avatar/index.md, and replace it with content from src/pages/guides/tts/index.md.
- src/pages/getting_started/usage/index.md -- remove Avatar API usage information. This involves limitations, input specifications, API parameters, API render time, Request limits.
- static/openapi/ttsapi.json -- remove `/avatars` list path, `/generate-avatar` path, update the response examples on `/status/{jobId}`.

Disable Text to Avatar feature

---

static/openapi/ttsapi.json

Fixed duplicate error scenario summary

---

src/pages/api/index.md

Update Redocly block with scrolloffset

---

src/pages/api/index.md

Add shell command to Redocly component

---

gatsby-config.js

Update gatsby-config.js with internal link tag

---

src/pages/getting_started/index.md

edit scopes syntax

---

src/pages/getting_started/usage/index.md
static/openapi/audio-video-api.json

https://github.com/AdobeDocs/ffs-audio-video-API/issues/33

Issue 33/update usage notes

---

static/openapi/audio-video-api.json

removed /v1 from TTSpath titles

---

static/openapi/audio-video-api.json

update extendedpropertymap and successresponse for avatars

---

src/pages/guides/avatar/index.md
src/pages/guides/index.md

update sample response in guide for tts avatar

---

src/pages/guides/avatar/index.md

Add curl commands for color and transparent backgrounds

---

static/openapi/audio-video-api.json

Support only wav input; Update error codes, messages

---

.github/workflows/dependabot-auto-merge.yml

Added dependabot auto merge

---

.github/workflows/auto-deploy.yml

Added auto-deploy workflow on merge with main.

Added auto-deploy.yml
